export const cards = [
    // MONSTERS
    { name: 'Goblin', type: 'MONSTER', cost: 0, attack: 4, durability: 0, effect: 'GoblinE', soulPts: 1 },
    { name: 'Goblin', type: 'MONSTER', cost: 0, attack: 4, durability: 0, effect: 'GoblinE', soulPts: 1 },
    { name: 'Lich', type: 'MONSTER', cost: 0, attack: 18, durability: 0, effect: 'LichE', soulPts: 4 },
    { name: 'Ooze', type: 'MONSTER', cost: 0, attack: 8, durability: 0, effect: 'OozeE', soulPts: 2 },
    { name: 'Ooze', type: 'MONSTER', cost: 0, attack: 8, durability: 0, effect: 'OozeE', soulPts: 2 },
    { name: 'Doom_Knight', type: 'MONSTER', cost: 0, attack: 17, durability: 0, effect: 'DKE', soulPts: 4 },
    { name: 'Doom_Knight', type: 'MONSTER', cost: 0, attack: 17, durability: 0, effect: 'DKE', soulPts: 4 },
    { name: 'Skeleton', type: 'MONSTER', cost: 0, attack: 3, durability: 0, effect: 'SkeletonE', soulPts: 1 },
    { name: 'Skeleton', type: 'MONSTER', cost: 0, attack: 3, durability: 0, effect: 'SkeletonE', soulPts: 1 },
    { name: 'Spider', type: 'MONSTER', cost: 0, attack: 8, durability: 0, effect: 'SpiderE', soulPts: 2 },
    { name: 'Spider', type: 'MONSTER', cost: 0, attack: 8, durability: 0, effect: 'SpiderE', soulPts: 2 },
    { name: 'Troll', type: 'MONSTER', cost: 0, attack: 16, durability: 0, effect: 'TrollE', soulPts: 4 },
    { name: 'Troll', type: 'MONSTER', cost: 0, attack: 16, durability: 0, effect: 'TrollE', soulPts: 4 },
    { name: 'Vampire', type: 'MONSTER', cost: 0, attack: 12, durability: 0, effect: 'VampireE', soulPts: 3 },
    { name: 'Vampire', type: 'MONSTER', cost: 0, attack: 12, durability: 0, effect: 'VampireE', soulPts: 3 },
    { name: 'Vermin', type: 'MONSTER', cost: 0, attack: 4, durability: 0, effect: 'VerminE', soulPts: 1 },
    { name: 'Vermin', type: 'MONSTER', cost: 0, attack: 4, durability: 0, effect: 'VerminE', soulPts: 1 },
    { name: 'Watcher', type: 'MONSTER', cost: 0, attack: 10, durability: 0, effect: 'WatcherE', soulPts: 10 },
    { name: 'Watcher', type: 'MONSTER', cost: 0, attack: 10, durability: 0, effect: 'WatcherE', soulPts: 10 },
    { name: 'Witch', type: 'MONSTER', cost: 0, attack: 12, durability: 0, effect: 'WitchE', soulPts: 3 },
    { name: 'Witch', type: 'MONSTER', cost: 0, attack: 12, durability: 0, effect: 'WitchE', soulPts: 3 },
    { name: 'Wraith', type: 'MONSTER', cost: 0, attack: 9, durability: 0, effect: 'WraithE', soulPts: 2 },
    { name: 'Wraith', type: 'MONSTER', cost: 0, attack: 9, durability: 0, effect: 'WraithE', soulPts: 2 },
    { name: 'Zombie', type: 'MONSTER', cost: 0, attack: 5, durability: 0, effect: 'ZombieE', soulPts: 1 },
    { name: 'Zombie', type: 'MONSTER', cost: 0, attack: 5, durability: 0, effect: 'ZombieE', soulPts: 1 },
  
    // ITEMS
    { name: 'Mystery_Potion', type: 'ITEM', cost: 1, attack: 0, durability: 3, effect: 'MPE', soulPts: 0 },
    { name: 'Mystery_Potion', type: 'ITEM', cost: 1, attack: 0, durability: 3, effect: 'MPE', soulPts: 0 },
    { name: 'Potion', type: 'ITEM', cost: 0, attack: 0, durability: 3, effect: 'PE', soulPts: 0 },
    { name: 'Stew', type: 'ITEM', cost: 1, attack: 0, durability: 3, effect: 'StewE', soulPts: 0 },
    { name: 'Talisman', type: 'ITEM', cost: 0, attack: 0, durability: 3, effect: 'TalismanE', soulPts: 0 },
    { name: 'Torch', type: 'ITEM', cost: 0, attack: 0, durability: 3, effect: 'TorchE', soulPts: 0 },
    { name: 'Treasure_Chest', type: 'ITEM', cost: 1, attack: 0, durability: 3, effect: 'TCE', soulPts: 0 },
    { name: 'Key', type: 'ITEM', cost: 0, attack: 0, durability: 3, effect: 'KeyE', soulPts: 0 },
  
    // WEAPONS
    { name: 'Blast_Wand', type: 'WEAPON', cost: 1, attack: 3, durability: 3, effect: 'BWE', soulPts: 0 },
    { name: 'Corruptor', type: 'WEAPON', cost: 2, attack: 5, durability: 2, effect: 'CorruptorE', soulPts: 0 },
    { name: 'Fork', type: 'WEAPON', cost: 0, attack: 2, durability: 3, effect: 'ForkE', soulPts: 0 },
    { name: 'Grimoire', type: 'WEAPON', cost: 2, attack: 5, durability: 3, effect: 'GrimoireE', soulPts: 0 },
    { name: 'Bloodthirster', type: 'WEAPON', cost: 1, attack: 4, durability: 3, effect: 'BloodthirsterE', soulPts: 0 },
    { name: 'Greataxe', type: 'WEAPON', cost: 1, attack: 4, durability: 2, effect: 'GreataxeE', soulPts: 0 },
    { name: 'Mallet', type: 'WEAPON', cost: 0, attack: 3, durability: 2, effect: 'MalletE', soulPts: 0 },
    { name: 'Shovel', type: 'WEAPON', cost: 1, attack: 4, durability: 3, effect: 'ShovelE', soulPts: 0 },
    { name: 'Soulfeeder', type: 'WEAPON', cost: 2, attack: 6, durability: 2, effect: 'SFE', soulPts: 0 },
    { name: 'Boomerang', type: 'WEAPON', cost: 0, attack: 3, durability: 2, effect: 'BoomerangE', soulPts: 0 },
    { name: 'Hookshot', type: 'WEAPON', cost: 2, attack: 5, durability: 3, effect: 'HookshotE', soulPts: 0 },
    { name: 'Repeater', type: 'WEAPON', cost: 2, attack: 8, durability: 2, effect: 'RepeaterE', soulPts: 0 },
    { name: 'Skewer', type: 'WEAPON', cost: 1, attack: 3, durability: 3, effect: 'SkewerE', soulPts: 0 },
    { name: 'Slingshot', type: 'WEAPON', cost: 1, attack: 4, durability: 3, effect: 'SlingshotE', soulPts: 0 },
    { name: 'Arcanife', type: 'WEAPON', cost: 1, attack: 4, durability: 3, effect: 'ArcanifeE', soulPts: 0 },
  
    // SPELLS
    { name: 'Blazing', type: 'SPELL', cost: 0, attack: 0, durability: 0, effect: 'BlazingE', soulPts: 0 },
    { name: 'Illuminate', type: 'SPELL', cost: 0, attack: 0, durability: 0, effect: 'IlluminateE', soulPts: 0 },
    { name: 'Illuminate', type: 'SPELL', cost: 0, attack: 0, durability: 0, effect: 'IlluminateE', soulPts: 0 },
    { name: 'Portal', type: 'SPELL', cost: 0, attack: 0, durability: 0, effect: 'PortalE', soulPts: 0 },
    { name: 'Portal', type: 'SPELL', cost: 0, attack: 0, durability: 0, effect: 'PortalE', soulPts: 0 },
    { name: 'Transmute', type: 'SPELL', cost: 1, attack: 0, durability: 0, effect: 'TransmuteE', soulPts: 0 },
    { name: 'Transmute', type: 'SPELL', cost: 1, attack: 0, durability: 0, effect: 'TransmuteE', soulPts: 0 },
    { name: 'Blazing', type: 'SPELL', cost: 0, attack: 0, durability: 0, effect: 'BlazingE', soulPts: 0 },
    { name: 'Upgrade', type: 'SPELL', cost: 1, attack: 0, durability: 0, effect: 'UpgradeE', soulPts: 0 },
    { name: 'Teleport', type: 'SPELL', cost: 0, attack: 0, durability: 0, effect: 'TeleportE', soulPts: 0 },
    { name: 'Teleport', type: 'SPELL', cost: 0, attack: 0, durability: 0, effect: 'TeleportE', soulPts: 0 },
  ];
  export const users = [
    {
        name: 'User',
        email: 'user@nextmail.com',
        password: '123456',
      },
  ]