export const cards = [
  // MONSTERS
  { name: 'Goblin', type: 'MONSTER', cost: 0, attack: 4, durability: 0, effectId: 'GoblinE', effectType: 'CE', soulPts: 1 },
  { name: 'Goblin', type: 'MONSTER', cost: 0, attack: 4, durability: 0, effectId: 'GoblinE', effectType: 'CE', soulPts: 1 },
  { name: 'Lich', type: 'MONSTER', cost: 0, attack: 18, durability: 0, effectId: 'LichE', effectType: 'CE', soulPts: 4 },
  { name: 'Ooze', type: 'MONSTER', cost: 0, attack: 8, durability: 0, effectId: 'OozeE', effectType: 'ETB', soulPts: 2 },
  { name: 'Ooze', type: 'MONSTER', cost: 0, attack: 8, durability: 0, effectId: 'OozeE', effectType: 'ETB', soulPts: 2 },
  { name: 'Doom_Knight', type: 'MONSTER', cost: 0, attack: 17, durability: 0, effectId: 'DKE', effectType: 'ETB', soulPts: 4 },
  { name: 'Doom_Knight', type: 'MONSTER', cost: 0, attack: 17, durability: 0, effectId: 'DKE', effectType: 'ETB', soulPts: 4 },
  { name: 'Skeleton', type: 'MONSTER', cost: 0, attack: 3, durability: 0, effectId: 'SkeletonE', effectType: 'ETB', soulPts: 1 },
  { name: 'Skeleton', type: 'MONSTER', cost: 0, attack: 3, durability: 0, effectId: 'SkeletonE', effectType: 'ETB', soulPts: 1 },
  { name: 'Spider', type: 'MONSTER', cost: 0, attack: 8, durability: 0, effectId: 'SpiderE', effectType: 'ETB', soulPts: 2 },
  { name: 'Spider', type: 'MONSTER', cost: 0, attack: 8, durability: 0, effectId: 'SpiderE', effectType: 'ETB', soulPts: 2 },
  { name: 'Troll', type: 'MONSTER', cost: 0, attack: 16, durability: 0, effectId: 'TrollE', effectType: 'ETB', soulPts: 4 },
  { name: 'Troll', type: 'MONSTER', cost: 0, attack: 16, durability: 0, effectId: 'TrollE', effectType: 'ETB', soulPts: 4 },
  { name: 'Vampire', type: 'MONSTER', cost: 0, attack: 12, durability: 0, effectId: 'VampireE', effectType: 'ETB', soulPts: 3 },
  { name: 'Vampire', type: 'MONSTER', cost: 0, attack: 12, durability: 0, effectId: 'VampireE', effectType: 'ETB', soulPts: 3 },
  { name: 'Vermin', type: 'MONSTER', cost: 0, attack: 4, durability: 0, effectId: 'VerminE', effectType: 'ETB', soulPts: 1 },
  { name: 'Vermin', type: 'MONSTER', cost: 0, attack: 4, durability: 0, effectId: 'VerminE', effectType: 'ETB', soulPts: 1 },
  { name: 'Watcher', type: 'MONSTER', cost: 0, attack: 10, durability: 0, effectId: 'WatcherE', effectType: 'CE', soulPts: 2},
  { name: 'Watcher', type: 'MONSTER', cost: 0, attack: 10, durability: 0, effectId: 'WatcherE', effectType: 'CE', soulPts: 2 },
  { name: 'Witch', type: 'MONSTER', cost: 0, attack: 12, durability: 0, effectId: 'WitchE', effectType: 'CE', soulPts: 3 },
  { name: 'Witch', type: 'MONSTER', cost: 0, attack: 12, durability: 0, effectId: 'WitchE', effectType: 'CE', soulPts: 3 },
  { name: 'Wraith', type: 'MONSTER', cost: 0, attack: 9, durability: 0, effectId: 'WraithE', effectType: 'CE', soulPts: 2 },
  { name: 'Wraith', type: 'MONSTER', cost: 0, attack: 9, durability: 0, effectId: 'WraithE', effectType: 'CE', soulPts: 2 },
  { name: 'Zombie', type: 'MONSTER', cost: 0, attack: 5, durability: 0, effectId: 'ZombieE', effectType: 'CE', soulPts: 1 },
  { name: 'Zombie', type: 'MONSTER', cost: 0, attack: 5, durability: 0, effectId: 'ZombieE', effectType: 'CE', soulPts: 1 },

  // ITEMS
  { name: 'Mystery_Potion', type: 'ITEM', cost: 1, attack: 0, durability: 3, effectId: 'MPE', effectType: 'AA', soulPts: 0 },
  { name: 'Mystery_Potion', type: 'ITEM', cost: 1, attack: 0, durability: 3, effectId: 'MPE', effectType: 'AA', soulPts: 0 },
  { name: 'Potion', type: 'ITEM', cost: 0, attack: 0, durability: 3, effectId: 'PE', effectType: 'AA', soulPts: 0 },
  { name: 'Stew', type: 'ITEM', cost: 1, attack: 0, durability: 3, effectId: 'StewE', effectType: 'AA', soulPts: 0 },
  { name: 'Talisman', type: 'ITEM', cost: 0, attack: 0, durability: 3, effectId: 'TalismanE', effectType: 'AA', soulPts: 0 },
  { name: 'Torch', type: 'ITEM', cost: 0, attack: 0, durability: 3, effectId: 'TorchE', effectType: 'AA', soulPts: 0 },
  { name: 'Treasure_Chest', type: 'ITEM', cost: 1, attack: 0, durability: 3, effectId: 'TCE', effectType: 'AA', soulPts: 0 },
  { name: 'Key', type: 'ITEM', cost: 0, attack: 0, durability: 3, effectId: 'KeyE', effectType: 'AA', soulPts: 0 },

  // WEAPONS
  { name: 'Blast_Wand', type: 'WEAPON', cost: 1, attack: 3, durability: 3, effectId: 'BWE', effectType: 'CE', soulPts: 0 },
  { name: 'Corruptor', type: 'WEAPON', cost: 2, attack: 5, durability: 2, effectId: 'CorruptorE', effectType: 'ETB', soulPts: 0 },
  { name: 'Fork', type: 'WEAPON', cost: 0, attack: 3, durability: 2, effectId: 'ForkE', effectType: 'ETB', soulPts: 0 },
  { name: 'Grimoire', type: 'WEAPON', cost: 2, attack: 5, durability: 3, effectId: 'GrimoireE', effectType: 'AA', soulPts: 0 },
  { name: 'Bloodthirster', type: 'WEAPON', cost: 1, attack: 4, durability: 3, effectId: 'BloodthirsterE', effectType: 'CE', soulPts: 0 },
  { name: 'Greataxe', type: 'WEAPON', cost: 1, attack: 4, durability: 2, effectId: 'GreataxeE', effectType: 'ETB', soulPts: 0 },
  { name: 'Mallet', type: 'WEAPON', cost: 0, attack: 3, durability: 2, effectId: 'MalletE', effectType: 'ETB', soulPts: 0 },
  { name: 'Shovel', type: 'WEAPON', cost: 1, attack: 4, durability: 3, effectId: 'ShovelE', effectType: 'AA', soulPts: 0 },
  { name: 'Soulfeeder', type: 'WEAPON', cost: 2, attack: 6, durability: 2, effectId: 'SFE', effectType: 'ETB', soulPts: 0 },
  { name: 'Boomerang', type: 'WEAPON', cost: 0, attack: 3, durability: 2, effectId: 'BoomerangE', effectType: 'CE', soulPts: 0 },
  { name: 'Hookshot', type: 'WEAPON', cost: 2, attack: 5, durability: 3, effectId: 'HookshotE', effectType: 'AA', soulPts: 0 },
  { name: 'Repeater', type: 'WEAPON', cost: 2, attack: 8, durability: 2, effectId: 'RepeaterE', effectType: 'CE', soulPts: 0 },
  { name: 'Skewer', type: 'WEAPON', cost: 1, attack: 3, durability: 3, effectId: 'SkewerE', effectType: 'CE', soulPts: 0 },
  { name: 'Slingshot', type: 'WEAPON', cost: 1, attack: 4, durability: 3, effectId: 'SlingshotE', effectType: 'ETB', soulPts: 0 },
  { name: 'Arcanife', type: 'WEAPON', cost: 1, attack: 4, durability: 3, effectId: 'ArcanifeE', effectType: 'AA', soulPts: 0 },

  // SPELLS
  { name: 'Blazing', type: 'SPELL', cost: 0, attack: 0, durability: 0, effectId: 'BlazingE', effectType: 'AA', soulPts: 0 },
  { name: 'Illuminate', type: 'SPELL', cost: 0, attack: 0, durability: 0, effectId: 'IlluminateE', effectType: 'AA', soulPts: 0 },
  { name: 'Illuminate', type: 'SPELL', cost: 0, attack: 0, durability: 0, effectId: 'IlluminateE', effectType: 'AA', soulPts: 0 },
  { name: 'Portal', type: 'SPELL', cost: 0, attack: 0, durability: 0, effectId: 'PortalE', effectType: 'AA', soulPts: 0 },
  { name: 'Portal', type: 'SPELL', cost: 0, attack: 0, durability: 0, effectId: 'PortalE', effectType: 'AA', soulPts: 0 },
  { name: 'Transmute', type: 'SPELL', cost: 1, attack: 0, durability: 0, effectId: 'TransmuteE', effectType: 'AA', soulPts: 0 },
  { name: 'Transmute', type: 'SPELL', cost: 1, attack: 0, durability: 0, effectId: 'TransmuteE', effectType: 'AA', soulPts: 0 },
  { name: 'Blazing', type: 'SPELL', cost: 0, attack: 0, durability: 0, effectId: 'BlazingE', effectType: 'AA', soulPts: 0 },
  { name: 'Upgrade', type: 'SPELL', cost: 1, attack: 0, durability: 0, effectId: 'UpgradeE', effectType: 'AA', soulPts: 0 },
  { name: 'Teleport', type: 'SPELL', cost: 0, attack: 0, durability: 0, effectId: 'TeleportE', effectType: 'AA', soulPts: 0 },
  { name: 'Teleport', type: 'SPELL', cost: 0, attack: 0, durability: 0, effectId: 'TeleportE', effectType: 'AA', soulPts: 0 },
];

  export const users = [
    {
        name: 'User',
        email: 'user@nextmail.com',
        password: '123456',
      },
  ]